spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.start.command=up
spring.docker.compose.stop.command=stop
spring.jpa.properties.hibernate.format_sql=true


spring.main.allow-circular-references=false
